use_frameworks!

platform :ios, '8.0'

target 'HWCommonConfigKit_Example' do
  pod 'HWCommonConfigKit', :path => '../'

  target 'HWCommonConfigKit_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
